#!/bin/bash

VER=$1
SUB=$2

rm -f repack_zip/clarity/zImage
rm -f repack_zip/system/lib/modules/*.ko

if [ ! -d repack_zip/system ]; then
	mkdir repack_zip/system
	mkdir repack_zip/system/lib
	mkdir repack_zip/system/lib/modules
fi

mv arch/arm64/boot/Image.gz-dtb repack_zip/clarity/zImage
find -name "*.ko" -exec mv {} repack_zip/system/lib/modules \;


