#!/bin/bash

rm -f repack_zip/clarity/zImage
rm -f repack_zip/system/lib/modules/*.ko
rm -f repack_zip/system/lib/modules/pronto/*.ko
rm -f drivers/platform/msm/ipa/ipa_common
rm -f arch/arm64/crypto/sha256-core.S
rm -f arch/arm64/crypto/sha512-core.S

make clean && make mrproper

